sequence:
  - service: media_player.sonos_snapshot
    data_template:
      entity_id: "{{ where }}"
  - service: tts.google_say
    data_template:
      entity_id: "{{ where }}"
      message: "{{ what }}"
  - delay: '00:00:03'
  - service: media_player.sonos_restore
    data_template:
      entity_id: "{{ where }}"
