sequence:
  - service: media_player.sonos_snapshot
    data_template:
      entity_id: media_player.kitchen
  - service: tts.google_say
    data_template:
      entity_id: media_player.kitchen
      message: 'Roberta has arrived at home'
  - delay: '00:00:03'
  - service: media_player.sonos_restore
    data_template:
      entity_id: media_player.kitchen
