alias: "Roberta Arrive Lights"
trigger:
  - platform: state
    #Roberta iPhone
    entity_id: device_tracker.d8a7fc928d9e415095072143d7cef2f2
    from: "not_home"
    to: "home"
condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
    - condition: state
      entity_id: light.kitchen
      state: "off"
action:
  - service: light.turn_on
    entity_id: light.kitchen
