  - platform: yweather
    monitored_conditions:
      - weather
      - weather_current
      - temperature
      - temp_min
      - temp_max
      - wind_speed
      - visibility
      - humidity
  - platform: template
    sensors:
      living_room_hub:
        value_template: '{{ states.remote.living_room_hub.attributes.current_activity }}'
        friendly_name: 'Living Room Harmony Hub'
  - platform: template
    sensors:
      kitchen_lock_battery:
        value_template: '{{ states.zwave.schlage_be468_touchscreen_deadbolt.attributes.battery_level }}'   
        unit_of_measurement: '%'
        friendly_name: 'Kitchen Lock Battery'
        icon_template: >-
          {% set battery_level = states.zwave.schlage_be468_touchscreen_deadbolt.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
          
  - platform: rest
    resource: "http://192.168.86.65/api/cFQZzCfzLlaBVVSEJamkZeCdwUI8F9vE2tSHn4L5/sensors/31"
    unit_of_measurement: Lux
    value_template: "{{ value_json.state.lightlevel }}"
    name: "Kitchen Lux"
    scan_interval: 2

  - platform: rest
    resource: "http://192.168.86.65/api/cFQZzCfzLlaBVVSEJamkZeCdwUI8F9vE2tSHn4L5/sensors/31"
    value_template: "{{ value_json.state.dark }}"
    name: "Kitchen Dark"
    scan_interval: 2

  - platform: rest
    resource: "http://192.168.86.65/api/cFQZzCfzLlaBVVSEJamkZeCdwUI8F9vE2tSHn4L5/sensors/29"
    unit_of_measurement: °C
    value_template: "{{ value_json.state.temperature | float / 100 }}"
    name: "Kitchen Temperature"
    scan_interval: 2
    
  - platform: rest
    resource: "http://192.168.86.65/api/cFQZzCfzLlaBVVSEJamkZeCdwUI8F9vE2tSHn4L5/sensors/41"
    templates: 
      rgb_color: "if (value_json.state.status === '0') return [251, 210, 41]; else return [54, 95, 140];"
    value_template: "{{ value_json.state.status }}"
    icon: "mdi:run"
    name: "Kitchen Motion"
    scan_interval: 2
     
  - platform: template
    sensors:
      kitchen_door_sensor:
        friendly_name: "Kitchen Door Sensor"
        value_template: >-
          {% if is_state('sensor.hank_doorwindow_sensor_access_control', '22') %}
            Open
          {% else %}
            Closed
          {% endif %} 
        icon_template: >-
          {% if is_state('sensor.hank_doorwindow_sensor_access_control', '22') %}
            mdi:door-open
          {% else %}
            mdi:door
          {% endif %}
      motion_kitchen:
        friendly_name: "Kitchen Motion"
        value_template: >-
          {% if is_state('sensor.kitchen_motion', '0') %}
            Idle
          {% else %}
            Movement
          {% endif %} 
        icon_template: >-
          {% if is_state('sensor.kitchen_motion', '0') %}
            mdi:run
          {% else %}
            mdi:run-fast
          {% endif %}   
      hank_hkzwdws01_doorwindow_sensor_battery_level:
        friendly_name: "Kitchen Door Sensor Battery"
        unit_of_measurement: '%'
        value_template: '{{ states.zwave.hank_hkzwdws01_doorwindow_sensor.attributes.battery_level|default(0) }}'
        icon_template: >-
          {% set battery_level = states.zwave.hank_hkzwdws01_doorwindow_sensor.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}  
      living_room_door_sensor:
        friendly_name: "Living Room Door"
        value_template: >-
          {% if is_state('sensor.hank_hkzwdws01_doorwindow_sensor_access_control', '22') %}
            Open
          {% else %}
            Closed
          {% endif %} 
        icon_template: >-
          {% if is_state('sensor.hank_hkzwdws01_doorwindow_sensor_access_control', '22') %}
            mdi:door-open
          {% else %}
            mdi:door
          {% endif %}
      living_room_door_sensor_battery:
        friendly_name: "Living Room Door Battery"
        unit_of_measurement: '%'
        value_template: '{{ states.zwave.hank_hkzwdws01_doorwindow_sensor_2.attributes.battery_level|default(0) }}'
        icon_template: >-
          {% set battery_level = states.zwave.hank_hkzwdws01_doorwindow_sensor_2.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}
      basement_door_sensor:
        friendly_name: "Basement Door"
        value_template: >-
          {% if is_state('sensor.hank_hkzwdws01_doorwindow_sensor_access_control_3', '22') %}
            Open
          {% else %}
            Closed
          {% endif %} 
        icon_template: >-
          {% if is_state('sensor.hank_hkzwdws01_doorwindow_sensor_access_control_3', '22') %}
            mdi:door-open
          {% else %}
            mdi:door
          {% endif %}
      basement_door_sensor_battery:
        friendly_name: "Basement Door Battery"
        unit_of_measurement: '%'
        value_template: '{{ states.zwave.hank_hkzwdws01_doorwindow_sensor_3.attributes.battery_level|default(0) }}'
        icon_template: >-
          {% set battery_level = states.zwave.hank_hkzwdws01_doorwindow_sensor_3.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %}    
      motion_bedroom:
        friendly_name: "Bedroom Motion"
        value_template: >-
          {% if is_state('sensor.vision_zp3102_pir_motion_sensor_burglar', '0') %}
            Idle
          {% else %}
            Movement
          {% endif %} 
        icon_template: >-
          {% if is_state('sensor.vision_zp3102_pir_motion_sensor_burglar', '0') %}
            mdi:run
          {% else %}
            mdi:run-fast
          {% endif %}
      motion_bedroom_battery:
        friendly_name: "Bedroom Motion Battery"
        unit_of_measurement: '%'
        value_template: '{{ states.zwave.vision_zp3102_pir_motion_sensor.attributes.battery_level|default(0) }}'
        icon_template: >-
          {% set battery_level = states.zwave.vision_zp3102_pir_motion_sensor.attributes.battery_level | default(0) | int %}
          {% set battery_round = (battery_level / 10) |int * 10 %}
          {% if battery_round >= 100 %}
            mdi:battery
          {% elif battery_round > 0 %}
            mdi:battery-{{ battery_round }}
          {% else %}
            mdi:battery-alert
          {% endif %} 